//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCabinetDentaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class employe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employe()
        {
            this.login_emp = new HashSet<login_emp>();
            this.rendez_vous = new HashSet<rendez_vous>();
            this.service_employe = new HashSet<service_employe>();
            this.traiter = new HashSet<traiter>();
        }
    
        public int Matricule { get; set; }
        public Nullable<int> Num_INP { get; set; }
        public string Nom_Emp { get; set; }
        public string Prenom_Emp { get; set; }
        public string Titre_cour { get; set; }
        public string CIN_Emp { get; set; }
        public string Fonction { get; set; }
        public string Sexe_Emp { get; set; }
        public decimal Salaire { get; set; }
        public System.DateTime Date_Embache { get; set; }
        public Nullable<System.DateTime> Date_Fin_Activite { get; set; }
        public System.DateTime Date_Naissance_Emp { get; set; }
        public string Type_Emp { get; set; }
        public string Telephone_Emp { get; set; }
        public string Adresse_Emp { get; set; }
        public byte[] Photo_Emp { get; set; }
        public string ApiKey { get; set; }
        public string ApiSecret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<login_emp> login_emp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rendez_vous> rendez_vous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<service_employe> service_employe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<traiter> traiter { get; set; }
    }
}
