//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCabinetDentaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class etat_paitent
    {
        public int Num_Etat { get; set; }
        public Nullable<bool> Anesthesie { get; set; }
        public Nullable<bool> Allergie { get; set; }
        public Nullable<bool> Saignement { get; set; }
        public Nullable<bool> Enceinte { get; set; }
        public string Autre_Etat { get; set; }
        public Nullable<int> NumPatEt { get; set; }
    
        public virtual paitent paitent { get; set; }
    }
}
