//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCabinetDentaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_emp
    {
        public int ID_Msg { get; set; }
        public System.DateTime Date_Msg { get; set; }
        public bool Lire_Msg { get; set; }
        public string Content_Msg { get; set; }
        public Nullable<int> IdLogMsg { get; set; }
        public Nullable<int> IdLogMsg2 { get; set; }
    
        public virtual login_emp login_emp { get; set; }
        public virtual login_emp login_emp1 { get; set; }
    }
}
