//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCabinetDentaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class paitent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public paitent()
        {
            this.etat_paitent = new HashSet<etat_paitent>();
            this.tuteur = new HashSet<tuteur>();
            this.rendez_vous = new HashSet<rendez_vous>();
            this.traiter = new HashSet<traiter>();
        }
    
        public int Num_Dossier { get; set; }
        public string Nom_Pat { get; set; }
        public string Prenom_Pat { get; set; }
        public string Sexe_Pat { get; set; }
        public bool CIN_Or_Pass { get; set; }
        public string CIN_Pass { get; set; }
        public System.DateTime Date_Naissance_Pat { get; set; }
        public string Adresse_Pat { get; set; }
        public string Email { get; set; }
        public string Nationalite { get; set; }
        public byte[] Photo_Pat { get; set; }
        public string Telephone_Pat { get; set; }
        public string Nature_Ass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etat_paitent> etat_paitent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tuteur> tuteur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rendez_vous> rendez_vous { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<traiter> traiter { get; set; }
    }
}
