//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCabinetDentaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock
    {
        public int ID_Mater { get; set; }
        public string Nom_Mater { get; set; }
        public Nullable<System.DateTime> DateDebut_Matr { get; set; }
        public Nullable<System.DateTime> DateFin_Matr { get; set; }
        public string Description_Matr { get; set; }
    }
}
