//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetCabinetDentaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class tranche
    {
        public int IDTra { get; set; }
        public Nullable<decimal> Partie { get; set; }
        public Nullable<System.DateTime> DateTra { get; set; }
        public Nullable<int> IdTraPay { get; set; }
    
        public virtual payement payement { get; set; }
    }
}
